version: '3'
services:
  app:
    image: 'biomann/softduplex:latest'
    container_name: softduplex
    environment:
      # Set to "true" to enable verbositiy
      VERBOSE: "false"
      REVERSE: "true"
    user: "0"
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    volumes:
      - /volume2/docker/softduplex/input/even:/input/even
      - /volume2/docker/softduplex/input/odd:/input/odd
      - /volume2/docker/paperless-ng/consume:/output
